site_name: MkDocs 1337
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt-br
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode 
      primary: deep-purple
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode   
      primary: teal
      accent: lime
    
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/gabrieldinizsm
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gabriel-diniz-42a73a165/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://github.com/gabrieldinizsm"  target="_blank" rel="noopener">Gabriel Diniz</a>